# Generated by Django 4.2.7 on 2023-12-11 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_post_options_post_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcomment',
            name='flair',
        ),
    ]
