# Generated by Django 4.2.7 on 2023-12-11 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_remove_postcomment_flair'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcomment',
            name='mentioned_users',
        ),
    ]
