# Generated by Django 4.2.7 on 2023-12-01 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_music_category_music_description_video_category_and_more'),
        ('comment_reply', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='music',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.music'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.video'),
        ),
    ]
